### ISSUE TITLE
Product page

### ISSUE THREAD

**Issue by mehrdad2** [negareh/gijin#4]
<img width="634" alt="e1" src="https://user-images.githubusercontent.com/4264683/40880427-c62ab3b8-66c5-11e8-9e7e-2fafdfcffd24.png">

**Comment by mehrdad2** [comment]
- [x] change 'Oil , Gass and Petrochemical industry' title to 'Oil and Gas Fasteners' .
- [x] change Manufacturers of all 'type' to 'Kinds'. 
- [x] make first box bigger.

**Comment by mehrdad2** [comment]
- [x] Part Name: w-14 Rail clip
       Material type: 'Spring Steel' to 'Spring Clip (w-14)'
- [x] Part Name: 'K-type Fastening system' to 'k-type clamp,Bolt & Nut'

**Comment by mehrdad2** [comment]
- [x] change 'Special Products' to 'Special and Customized Fasteners'

**Comment by mehrdad2** [comment]
- [x] change
'Producer of all kinds of fasteners using in railway , petrochemical and construction industries'
to
'Producer of all kinds of fasteners being used in railway , petrochemical and construction industries'

**Comment by shimafaraji** [comment]
Done
